# workflow to run Fuzzing tests
name: Fuzz CI
# Controls when the action will run
on:
  pull_request:
    branches: master
  push:
    branches: master
  schedule:
    - cron: 0 0 * * *  # run every day at UTC 00:00
  workflow_dispatch: # temp manual trigger

jobs:
  build-and-fuzz:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Docker
        run: docker build -t verify-c-common:fuzz . --file docker/verify-c-common-fuzz.Dockerfile

      - name: Run Tests and collect coverage
        run: docker run -v $(pwd):/host verify-c-common:fuzz /bin/bash -c \
          "mkdir /home/usea/verify-c-common/fuzzing_coverage &&
          cd build && ctest -R fuzz --timeout 2000 &&
          python3 /home/usea/verify-c-common/scripts/get_fuzzing_coverage.py --html-dir=/home/usea/verify-c-common/fuzzing_coverage &&
          mv /home/usea/verify-c-common/data/fuzz_coverage/all_fuzz.info /host &&
          cp -r /home/usea/verify-c-common/fuzzing_coverage /host/fuzzing_coverage"

      - name: Push and deploy
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b coverage-pages
          git add fuzzing_coverage
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -m "Update fuzzing coverage in gh actions"
          git push -f origin HEAD:gh-pages

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./all_fuzz.info
          name: codecov-verify-c-common
          fail_ci_if_error: true
          verbose: true
