# workflow to run Fuzzing tests
name: Fuzz CI
# Controls when the action will run
on:
  pull_request:
    branches: master
  schedule:
    - cron: 0 0 * * *  # run every day at UTC 00:00
  workflow_dispatch: # temp manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Docker
        run: docker build -t verify-c-common:fuzz . --file docker/verify-c-common-fuzz.Dockerfile

      - name: Run Tests and collect coverage
        run: docker run -v $(pwd):/host verify-c-common:fuzz /bin/bash -c "cd build && ctest -R fuzz --timeout 2000 && python3 /home/usea/verify-c-common/scripts/get_fuzzing_coverage.py && mv /home/usea/verify-c-common/data/fuzz_coverage/all_fuzz.info /host"

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./all_fuzz.info
          name: codecov-verify-c-common
          fail_ci_if_error: true
          verbose: true